server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    name: what-to-eat
    url: jdbc:mysql://localhost:3306/what_to_eat
    username: wte_user
    password: password
  liquibase:
    user: wte_admin
    password: password
    enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      show-sql: true
debug: true