DROP DATABASE IF EXISTS what_to_eat;
DROP USER IF EXISTS `wte_admin`@`%`;
DROP USER IF EXISTS `wte_user`@`%`;
CREATE DATABASE IF NOT EXISTS what_to_eat CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `wte_admin`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `what_to_eat`.* TO `wte_admin`@`%`;
CREATE USER IF NOT EXISTS `wte_user`@`%` IDENTIFIED BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `what_to_eat`.* TO `wte_user`@`%`;
FLUSH PRIVILEGES;